version: '3.8'
networks:
  helpdesk_network:   # Define a custom network
    driver: overlay    # You can specify the driver if needed
services:
  helpdesk:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5549:5549"
    volumes:
      - ./src:/var/www/html
    deploy:
      replicas: 1
    networks:
      helpdesk_network:
        external: true