# BAD
version: '3.8'
services:
  php:
    image: helpdesk
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "5541:5541"
      - "3306:3306"
    volumes:
      - ./src:/var/www/html
