version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5541:80"
      - "3306:3306"
    volumes:
      - ./src:/var/www/html
    deploy:
      replicas: 3