echo download from git.................................................................................
git pull origin

docker build -t php_8.3-helpdesk .
echo crate service.....................................................................................
docker service create --name helpdesk --replicas 3 --publish 5541:5541 helpdesk